dist: xenial
language: node_js
node_js:
    - "11.0"
before_install:
    - curl -L https://github.com/getzola/zola/releases/download/v0.5.1/zola-v0.5.1-x86_64-unknown-linux-gnu.tar.gz | tar xz
    - npm i -g firebase-tools
script:
    - ./zola build
    - rm zola
after_success:
    - firebase deploy -P blog-6dfa0
