dist: xenial
language: minimal
before_install:
    - curl -L https://github.com/getzola/zola/releases/download/v0.5.1/zola-v0.5.1-x86_64-unknown-linux-gnu.tar.gz | tar xz
script:
    - ls -al
    - ./zola build
