dist: xenial
language: node_js
node_js:
    - "11.0"
before_install:
    - curl -L https://github.com/getzola/zola/releases/download/v0.5.1/zola-v0.5.1-x86_64-unknown-linux-gnu.tar.gz | tar xz
    - npm i -g firebase-tools
script:
    - ./zola build
    - rm zola
deploy:
    provider: firebase
    project: "blog-6dfa0"
    token:
        secure: "Xd+xLSNy2RU1bQVAdvdj1r6lg/ct9Yk2Zk1AhG13k5lu4O2VIlL3ygqfiGtE/cdPA5G9TsGReGmfBW9e/M7+Kz1kmCge3fW0CbemWrsy3Rk5Ar0NhZiJJLhcFTU1fljJjwmbuaW832CIX5TJ9m+keT8sLUUpNIzXSMAU9O6+ctiAOnBa0l3PK7IW7y5HFYkfvt+ukVgXK7i2S2CVpQiN+1PFBX2T26R9sMfzSDRJ+nIflLOKDCWpyqCj8QEzwijuMlctjXBf/o92yGYBx+tntMEBvXWXaQT90eqdGuO8Op4BNhw1OiFmfpZgbz2LGBzxRjEsFWYMTSL0Lzft6Vpg7QUiVuTdYen4ZN3y1kvZ41so45YVFZ81sCFIMq69V5ZeRp6+sB9sbEixR1WHtJC0bLNAMy40kUL2UwqAJbBdh4ocD+pFo5Tlq8WTEU3Tu0aqgBlU9UjwAkRMpIo/8jye7V1jGPq9Yie+M34V4rfUYdlIdqZXF5dyZwiCyvMx4bSUTaAs5ouH4yIXIyPocLHpe4DcD9yAMWuPaEBhgIUCml6/Fd8mhqhl8DpTFxJIiwxC7xizIzJVjOoqKGm93ZLJLljoxgzUXPYQf9tRktINJaLDruvosPL1pkjB9JMOYy5G79942bSGPtBodmMbVIPGxBHbmSSu+bLWy0J18azxCJI="
